### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by surfpat** [abeudin/searx_ynh#24]
Hello
support the Search button
gives me this error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

my /var/log/uwsgi/app/searx.log

[searx.txt](https://github.com/abeudin/searx_ynh/files/53809/searx.txt)

**Comment by b01xy** [comment]
Hello,
same here on raspi 2 Jessie

2 things in the log : 

SSLError: <unprintable SSLError object>

Mon Dec  7 14:38:13 2015 - running /usr/bin/uwsgi-core
[uWSGI] getting INI configuration from /usr/share/uwsgi/conf/default.ini
realpath() of /etc/uwsgi/apps-enabled/searx.ini failed: No such file or directory [core/utils.c line 3591]

++
b

**Comment by abeudin** [comment]
you can do 
ls /etc/uwsgi

**Comment by b01xy** [comment]
```bash
admin@raspberrypi:~ $ ls /etc/uwsgi 
apps-available  apps-enabled
admin@raspberrypi:~ $ ls /etc/uwsgi/apps-enabled/
README  searx.ini
admin@raspberrypi:/etc/uwsgi/apps-enabled $ cat searx.ini 
[uwsgi]
# Who will run the code
uid = searx
gid = searx

# Number of workers
workers = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python

# Application base folder
base = /opt/yunohost/searx

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /opt/yunohost/searx/
pythonpath = /opt/yunohost/searx/
chdir = /opt/yunohost/searx/searx/

# The variable holding flask application
callable = app
'''

**Comment by abeudin** [comment]
i think is the same bug https://github.com/asciimoo/searx/issues/463

**Comment by surfpat** [comment]
I disable google but the problem is still there

**Comment by surfpat** [comment]
I find a procedure
https://dev.yunohost.org/issues/73
problem solved
